# Generated by Django 5.2 on 2025-04-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_usuario_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
